version: "3.7"
services:
  app:
    container_name: express-mongo-app
    restart: always
    build: ./app
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - mongo
      - mongo-express

  mongo:
        image: mongo
        command: "mongod --smallfiles"
        ports:
          - "27017:27017"
        env_file: .env
        volumes:
          - ${PWD}/data/db:${MONGO_DATA_DIR}
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
            - mongo

    